version: "3.3"
services:
  spark-master:
    image: conduct-ml-pyspark:0.3
    ports:
      - "9090:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
       - ./app:/job/app
       - ./data:/job/data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: conduct-ml-pyspark:0.3
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./app:/job/app
       - ./data:/job/data
  spark-worker-b:
    image: conduct-ml-pyspark:0.3
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
       - ./app:/job/app
       - ./data:/job/data

#  demo-database:
#    image: postgres:11.7-alpine
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=casa1234

